`timescale 1ns/1ps

`ifndef CORDIC_PKG_SV
`define CORDIC_PKG_SV

// ============================================================
// cordic_pkg.sv
//
// Shared parameters and constants for the 16-stage pipelined
// CORDIC sine/cosine accelerator.
//
// Fixed-point format:
//   Q2.14 signed fixed-point
//   Total width      = 16 bits
//   Fractional bits  = 14 bits
//   Scale factor     = 2^14 = 16384
//
// Supported input angle range for initial version:
//   -pi/2 to +pi/2 radians
//
// Algorithm:
//   Rotation-mode CORDIC
// ============================================================

package cordic_pkg;

  // ------------------------------------------------------------
  // Global configuration
  // ------------------------------------------------------------

  parameter int DATA_WIDTH = 16;
  parameter int FRAC_BITS  = 14;
  parameter int STAGES     = 16;

  parameter int SCALE      = 1 << FRAC_BITS;

  // ------------------------------------------------------------
  // Fixed-point type
  // ------------------------------------------------------------
  //
  // q2_14_t is a signed 16-bit fixed-point type.
  //
  // Examples:
  //   16'sd0      =  0.0
  //   16'sd16384  =  1.0
  //   16'sd8192   =  0.5
  //   -16'sd8192  = -0.5
  //
  // Note:
  //   Q2.14 range is approximately -2.0 to +1.9999.
  // ------------------------------------------------------------

  typedef logic signed [DATA_WIDTH-1:0] q2_14_t;

  // ------------------------------------------------------------
  // CORDIC gain compensation constant
  // ------------------------------------------------------------
  //
  // Rotation-mode CORDIC has a gain of approximately 1.64676.
  // To compensate, the initial x value is set to:
  //
  //   K = 0.607252935103
  //
  // Q2.14 conversion:
  //
  //   round(0.607252935103 * 16384) = 9949
  //
  // Therefore:
  //
  //   x_0 = CORDIC_K
  //   y_0 = 0
  //   z_0 = input_angle
  // ------------------------------------------------------------

  localparam q2_14_t CORDIC_K = 16'sd9949;

  // ------------------------------------------------------------
  // Arctangent lookup table
  // ------------------------------------------------------------
  //
  // ATAN_TABLE[i] = atan(2^-i), represented in Q2.14 radians.
  //
  // These values are generated by scripts/gen_golden.py.
  //
  // Scale factor:
  //   fixed_value = round(atan(2^-i) * 2^14)
  // ------------------------------------------------------------

  localparam q2_14_t ATAN_TABLE [0:STAGES-1] = '{
      16'sd12868,  // atan(2^-0)  = 0.785398163397 rad
      16'sd7596,   // atan(2^-1)  = 0.463647609001 rad
      16'sd4014,   // atan(2^-2)  = 0.244978663127 rad
      16'sd2037,   // atan(2^-3)  = 0.124354994547 rad
      16'sd1023,   // atan(2^-4)  = 0.062418809996 rad
      16'sd512,    // atan(2^-5)  = 0.031239833430 rad
      16'sd256,    // atan(2^-6)  = 0.015623728620 rad
      16'sd128,    // atan(2^-7)  = 0.007812341060 rad
      16'sd64,     // atan(2^-8)  = 0.003906230132 rad
      16'sd32,     // atan(2^-9)  = 0.001953122516 rad
      16'sd16,     // atan(2^-10) = 0.000976562189 rad
      16'sd8,      // atan(2^-11) = 0.000488281211 rad
      16'sd4,      // atan(2^-12) = 0.000244140620 rad
      16'sd2,      // atan(2^-13) = 0.000122070312 rad
      16'sd1,      // atan(2^-14) = 0.000061035156 rad
      16'sd0       // atan(2^-15) = 0.000030517578 rad
  };

endpackage

`endif
